In [1]:
import os                                                                               # Работа с файловой системой
import sys                                                                              # Системные функции
import math                                                                             # Математические операции
import asyncio                                                                          # Асинхронные функции      
import pickle                                                                           # Сериализация объектов (сохранение моделей)      
import clickhouse_connect                                                               # Драйвер для связи с БД   

import numpy as np                                                                      # Работа с векторами и матрицами           
import polars as pl                                                                     # Работа с таблицами (быстрая)   
import pandas as pd                                                                     # Работа с таблицами (простая)     
import polars.selectors as cs                                                           # Фильтр столбцов polars
import seaborn as sns                                                                   # Простые 2d графики
import matplotlib.pyplot as plt                                                         # Базовая визуализация   
import plotly.graph_objects as go                                                       # Интерактивные 3d графики   

from pathlib import Path                                                                # Работа с путями к файлам
from sklearn import model_selection, decomposition, metrics, linear_model               # Машинное обучение (PCA, logreg, metrics)
from scipy.cluster import hierarchy                                                     # Иерархическая кластеризация
from scipy.spatial import distance, KDTree                                              # Работа с матрицами расстояний
from tqdm import tqdm                                                                   # Отслежевание прогресса
from tqdm.asyncio import tqdm as async_tqdm                                             # Отслежевание прогресса при асинхронных запросах
from importlib.metadata import version                                                  # Вывод информации о библиотеках Python
from collections.abc import Callable                                                    # Подсказки типов
from lib import clickhouse_tools as ch

In [2]:
print(f"Python {sys.version}")
libs = ["clickhouse_connect", "numpy", "pandas", "polars", "seaborn", "matplotlib", "plotly", "scikit-learn", "scipy", "tqdm"]
for lib in libs:
    print(lib, version(lib))

Python 3.14.8 | packaged by conda-forge | (main, Oct  7 2026, 00:23:19) [GCC 15.3.0]
clickhouse_connect 1.10.0
numpy 2.5.3
pandas 3.0.6
polars 2.0.0
seaborn 0.13.2
matplotlib 3.11.2
plotly 7.1.0
scikit-learn 1.9.1
scipy 1.18.1
tqdm 4.70.1

In [3]:
config = ch.Config("../.env")
run_date = "2026-10-08"
step_folder = Path(f"../steps/1/{run_date}")
step_folder.mkdir(parents=True, exist_ok=True)
parameters = {
    "RANDOM_STATE"                    : 9,                             #  Фиксированное состояние генератора случайных чисел (для воспроизводимости)
    "EXCLUDED_CHROMOSOMES"            : ["chrX","chrY","chrM"],        #  Черный список хромосом (фильтр №1)
    "RATE_TOTAL_THRESHOLD"            : 0.8,                           #  Фильтр №2  
    "RATE_CLEAN_DEEP_THRESHOLD"       : 0.5,                           #  Фильтр №3
    "MEDIAN_DEPTH_MIN_THRESHOLD"      : 10,                            #  Фильтр №4 нижняя граница 
    "MEDIAN_DEPTH_MAX_THRESHOLD"      : 100,                           #  Фильтр №4 верхняя граница  
    "STD_BETA_THRESHOLD"              : 20,                            #  Фильтр №5  
    "TOTAL_MIN_AVG_DEPTH"             : 10,                            #  Фильтр качества образцов
    "SSB_QUANTILE_THRESHOLD"          : 0.95,                          #  Фильтр №6 верхняя граница
    "SSW_QUANTILE_THRESHOLD"          : 0.05,                          #  Фильтр №6 нижняя граница
    "MAX_CONCURRENT_QUERIES"          : 4,                             #  Кол-во одновременных запросов к БД
    "IMPUTE_WINDOW_SIZE"              : 500                            #  Размер окна импутации (восстановления) данных
}

## Prepare groups

In [4]:
raw_samplesheet = pl.read_excel("../data/samplesheet.xlsx")
raw_samplesheet

shape: (324, 4)
┌─────┬───────────┬──────────────┬─────────┐
│ id  ┆ btk_short ┆ btk_id       ┆ include │
│ --- ┆ ---       ┆ ---          ┆ ---     │
│ str ┆ i64       ┆ str          ┆ i64     │
╞═════╪═══════════╪══════════════╪═════════╡
│ K1  ┆ 7045200   ┆ 000007045200 ┆ 1       │
│ K2  ┆ 7042670   ┆ 000007042670 ┆ 1       │
│ K3  ┆ 7103280   ┆ 000007103280 ┆ 1       │
│ K4  ┆ 7103250   ┆ 000007103250 ┆ 0       │
│ K5  ┆ 7104070   ┆ 000007104070 ┆ 0       │
│ …   ┆ …         ┆ …            ┆ …       │
│ N44 ┆ 7030340   ┆ 000007030340 ┆ 1       │
│ N43 ┆ 7030350   ┆ 000007030350 ┆ 1       │
│ N42 ┆ 7030360   ┆ 000007030360 ┆ 1       │
│ N41 ┆ 7030410   ┆ 000007030410 ┆ 1       │
│ N1  ┆ 7030450   ┆ 000007030450 ┆ 1       │
└─────┴───────────┴──────────────┴─────────┘

In [5]:
samplesheet = raw_samplesheet.filter(
    pl.col("include") == 1
).with_columns(
    pl.when(pl.col("id").str.starts_with("K"))
    .then(pl.lit("Kabuki"))
    .otherwise(
        pl.when(pl.col("id").str.starts_with("RSTS"))
        .then(pl.lit("RSTS"))
        .otherwise(
            pl.when(pl.col("id").str.starts_with("sot"))
            .then(pl.lit("Sotos"))
            .otherwise(
                pl.lit("Normal")
            )
        )
    )
    .alias("group"),
)
samplesheet

shape: (155, 5)
┌─────┬───────────┬──────────────┬─────────┬────────┐
│ id  ┆ btk_short ┆ btk_id       ┆ include ┆ group  │
│ --- ┆ ---       ┆ ---          ┆ ---     ┆ ---    │
│ str ┆ i64       ┆ str          ┆ i64     ┆ str    │
╞═════╪═══════════╪══════════════╪═════════╪════════╡
│ K1  ┆ 7045200   ┆ 000007045200 ┆ 1       ┆ Kabuki │
│ K2  ┆ 7042670   ┆ 000007042670 ┆ 1       ┆ Kabuki │
│ K3  ┆ 7103280   ┆ 000007103280 ┆ 1       ┆ Kabuki │
│ K6  ┆ 7044630   ┆ 000007044630 ┆ 1       ┆ Kabuki │
│ K7  ┆ 7027610   ┆ 000007027610 ┆ 1       ┆ Kabuki │
│ …   ┆ …         ┆ …            ┆ …       ┆ …      │
│ N44 ┆ 7030340   ┆ 000007030340 ┆ 1       ┆ Normal │
│ N43 ┆ 7030350   ┆ 000007030350 ┆ 1       ┆ Normal │
│ N42 ┆ 7030360   ┆ 000007030360 ┆ 1       ┆ Normal │
│ N41 ┆ 7030410   ┆ 000007030410 ┆ 1       ┆ Normal │
│ N1  ┆ 7030450   ┆ 000007030450 ┆ 1       ┆ Normal │
└─────┴───────────┴──────────────┴─────────┴────────┘

In [6]:
samplesheet["group"].value_counts()

shape: (4, 2)
┌────────┬───────┐
│ group  ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u64   │
╞════════╪═══════╡
│ Kabuki ┆ 18    │
│ RSTS   ┆ 57    │
│ Normal ┆ 64    │
│ Sotos  ┆ 16    │
└────────┴───────┘

In [7]:
samples_with_db_info = ch.get_samples(config.get_client(), samplesheet["btk_id"].to_list()).with_columns(
    pl.col("btk_id").cast(pl.String).alias("btk_id"),
    percent_valid_sites = pl.col("n_valid_sites") / pl.col("covered_sites")*100    
).join(
    samplesheet, on = "btk_id", how = "inner"
).filter(
    pl.col("mean_depth") >= parameters["TOTAL_MIN_AVG_DEPTH"]
)
samples_with_db_info

ВНИМАНИЕ! Число переданных идентификаторов не совпадает с количеством образцов.

shape: (109, 15)
┌──────────────┬──────────────┬─────────────┬─────────────┬───┬─────┬───────────┬─────────┬────────┐
│ btk_id       ┆ medical_reco ┆ bam_path    ┆ bed_path    ┆ … ┆ id  ┆ btk_short ┆ include ┆ group  │
│ ---          ┆ rd           ┆ ---         ┆ ---         ┆   ┆ --- ┆ ---       ┆ ---     ┆ ---    │
│ str          ┆ ---          ┆ str         ┆ str         ┆   ┆ str ┆ i64       ┆ i64     ┆ str    │
│              ┆ str          ┆             ┆             ┆   ┆     ┆           ┆         ┆        │
╞══════════════╪══════════════╪═════════════╪═════════════╪═══╪═════╪═══════════╪═════════╪════════╡
│ 000007045200 ┆ 3934/2024    ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ K1  ┆ 7045200   ┆ 1       ┆ Kabuki │
│              ┆              ┆ 2025/05/4-O ┆ 2025/05/4-O ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ NT/00000…   ┆ NT/00000…   ┆   ┆     ┆           ┆         ┆        │
│ 000007042670 ┆ 2847/2024    ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ K2  ┆ 7042670   ┆ 1       ┆ Kabuki │
│              ┆              ┆ 2025/05/5-O ┆ 2025/05/5-O ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ NT/00000…   ┆ NT/00000…   ┆   ┆     ┆           ┆         ┆        │
│ 000007103280 ┆ 20936/2024   ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ K3  ┆ 7103280   ┆ 1       ┆ Kabuki │
│              ┆              ┆ 2025/06/24- ┆ 2025/06/24- ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ ONT/0000…   ┆ ONT/0000…   ┆   ┆     ┆           ┆         ┆        │
│ 000007044630 ┆ 4940/2024    ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ K6  ┆ 7044630   ┆ 1       ┆ Kabuki │
│              ┆              ┆ 2025/05/4-O ┆ 2025/05/4-O ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ NT/00000…   ┆ NT/00000…   ┆   ┆     ┆           ┆         ┆        │
│ 000007027610 ┆ 24367/2022   ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ K7  ┆ 7027610   ┆ 1       ┆ Kabuki │
│              ┆              ┆ 2024/06/2-O ┆ 2024/06/2-O ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ NT/00000…   ┆ NT/00000…   ┆   ┆     ┆           ┆         ┆        │
│ …            ┆ …            ┆ …           ┆ …           ┆ … ┆ …   ┆ …         ┆ …       ┆ …      │
│ 000007030290 ┆ 32004/2023   ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ N45 ┆ 7030290   ┆ 1       ┆ Normal │
│              ┆              ┆ 2024/06/21- ┆ 2024/06/21- ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ ONT/0000…   ┆ ONT/0000…   ┆   ┆     ┆           ┆         ┆        │
│ 000007030340 ┆ 24683/2020   ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ N44 ┆ 7030340   ┆ 1       ┆ Normal │
│              ┆              ┆ 2024/06/21- ┆ 2024/06/21- ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ ONT/0000…   ┆ ONT/0000…   ┆   ┆     ┆           ┆         ┆        │
│ 000007030350 ┆ 24683/2020   ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ N43 ┆ 7030350   ┆ 1       ┆ Normal │
│              ┆              ┆ 2024/06/21- ┆ 2024/06/21- ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ ONT/0000…   ┆ ONT/0000…   ┆   ┆     ┆           ┆         ┆        │
│ 000007030360 ┆ 2674/2021    ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ N42 ┆ 7030360   ┆ 1       ┆ Normal │
│              ┆              ┆ 2024/06/21- ┆ 2024/06/21- ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ ONT/0000…   ┆ ONT/0000…   ┆   ┆     ┆           ┆         ┆        │
│ 000007030410 ┆ 37408/2023   ┆ /media/BTK/ ┆ /media/BTK/ ┆ … ┆ N41 ┆ 7030410   ┆ 1       ┆ Normal │
│              ┆              ┆ 2024/06/21- ┆ 2024/06/21- ┆   ┆     ┆           ┆         ┆        │
│              ┆              ┆ ONT/0000…   ┆ ONT/0000…   ┆   ┆     ┆           ┆         ┆        │
└──────────────┴──────────────┴─────────────┴─────────────┴───┴─────┴───────────┴─────────┴────────┘

In [8]:
samples_with_db_info["group"].value_counts()

shape: (4, 2)
┌────────┬───────┐
│ group  ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u64   │
╞════════╪═══════╡
│ Normal ┆ 59    │
│ Sotos  ┆ 15    │
│ Kabuki ┆ 17    │
│ RSTS   ┆ 18    │
└────────┴───────┘

In [9]:
to_split = samples_with_db_info.to_pandas()
sample_train, sample_val = model_selection.train_test_split(to_split, test_size = 0.3, stratify = to_split["group"], random_state=parameters["RANDOM_STATE"])
sample_train["group"].value_counts()

group
Normal    41
RSTS      13
Kabuki    12
Sotos     10
Name: count, dtype: int64

In [10]:
sample_val["group"].value_counts()

group
Normal    18
Sotos      5
RSTS       5
Kabuki     5
Name: count, dtype: int64

In [11]:
sample_train = sample_train.sort_values("btk_id")
sample_val = sample_val.sort_values("btk_id")
samples_with_db_info_sorted = samples_with_db_info.to_pandas().sort_values("btk_id")
sample_train.to_csv(step_folder / "train_samples.csv", index = False)
sample_val.to_csv(step_folder / "val_samples.csv", index = False)
samples_with_db_info_sorted.to_csv(step_folder / "total_info.csv", index = False)

## Filtering

In [12]:
cpg = pl.read_csv("../data/CpG.bed",separator="\t",has_header=True).\
    select(
        ["seqnames","start"]
    ).\
    filter(
        ~pl.col("seqnames").is_in(parameters['EXCLUDED_CHROMOSOMES'])
    )
cpg.columns = ["chr","start"]
print(cpg.shape)
cpg.head()

(27852739, 2)

shape: (5, 2)
┌──────┬───────┐
│ chr  ┆ start │
│ ---  ┆ ---   │
│ str  ┆ i64   │
╞══════╪═══════╡
│ chr1 ┆ 10468 │
│ chr1 ┆ 10470 │
│ chr1 ┆ 10483 │
│ chr1 ┆ 10488 │
│ chr1 ┆ 10492 │
└──────┴───────┘

In [13]:
semaphore = asyncio.Semaphore(parameters['MAX_CONCURRENT_QUERIES'])
batches = ch.get_batches(cpg, batch_size = 100000)    
    
requests = [ch.task(ch.get_descriptive_statistics, semaphore, batch, i, sample_train["btk_id"].to_list(), parameters, config) for i, batch in batches]
results = await async_tqdm.gather(*requests)
list_stats = [df for _, df in results if df is not None]
descriptive = pl.concat(list_stats)
descriptive.write_csv(step_folder / "locus_descriptive_statistics.csv")
descriptive

100%|██████████| 290/290 [16:16<00:00,  3.37s/it]

shape: (208_162, 7)
┌───────┬──────────┬──────────┬──────────────┬───────────┬───────────┬──────────────┐
│ chr   ┆ pos      ┆ not_null ┆ n_clean_deep ┆ beta_mean ┆ beta_std  ┆ median_depth │
│ ---   ┆ ---      ┆ ---      ┆ ---          ┆ ---       ┆ ---       ┆ ---          │
│ str   ┆ u32      ┆ u64      ┆ u64          ┆ f64       ┆ f64       ┆ f64          │
╞═══════╪══════════╪══════════╪══════════════╪═══════════╪═══════════╪══════════════╡
│ chr1  ┆ 916945   ┆ 76       ┆ 39           ┆ 26.475132 ┆ 20.534152 ┆ 12.0         │
│ chr1  ┆ 868039   ┆ 76       ┆ 49           ┆ 57.041316 ┆ 21.051241 ┆ 13.0         │
│ chr1  ┆ 3323244  ┆ 76       ┆ 40           ┆ 19.587368 ┆ 20.345529 ┆ 11.5         │
│ chr1  ┆ 1759017  ┆ 76       ┆ 47           ┆ 38.093421 ┆ 25.805114 ┆ 14.0         │
│ chr1  ┆ 3120391  ┆ 76       ┆ 60           ┆ 56.678553 ┆ 23.887965 ┆ 13.5         │
│ …     ┆ …        ┆ …        ┆ …            ┆ …         ┆ …         ┆ …            │
│ chr22 ┆ 50547479 ┆ 76       ┆ 48           ┆ 49.9525   ┆ 24.948064 ┆ 14.0         │
│ chr22 ┆ 50387685 ┆ 76       ┆ 66           ┆ 58.868684 ┆ 20.095565 ┆ 18.0         │
│ chr22 ┆ 49634562 ┆ 76       ┆ 46           ┆ 54.336842 ┆ 21.294253 ┆ 13.0         │
│ chr22 ┆ 50084298 ┆ 76       ┆ 47           ┆ 29.2875   ┆ 21.368036 ┆ 13.0         │
│ chr22 ┆ 50300190 ┆ 76       ┆ 43           ┆ 46.043947 ┆ 23.580604 ┆ 13.0         │
└───────┴──────────┴──────────┴──────────────┴───────────┴───────────┴──────────────┘

In [14]:
semaphore = asyncio.Semaphore(parameters['MAX_CONCURRENT_QUERIES'])
batches = ch.get_batches(descriptive, batch_size = 10000)    
    
requests = [ch.task(ch.get_methylation_data, semaphore, batch, i, sample_train["btk_id"].to_list(), config) for i, batch in batches]
results = await async_tqdm.gather(*requests)
list_res = [df for _, df in results if df is not None]
for i in range(1,len(list_res)):
    list_res[i] = list_res[i].drop("btk_id")# Удалим столбец с идентификаторами из всех порций кроме первой
data_train_raw = pl.concat(list_res,how="horizontal")
data_train_raw.write_csv(step_folder / "data_train_raw.csv")
data_train_raw

100%|██████████| 33/33 [06:29<00:00, 11.81s/it]

shape: (76, 208_163)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ btk_id    ┆ chr1_2160 ┆ chr1_2161 ┆ chr1_2168 ┆ … ┆ chr22_471 ┆ chr22_471 ┆ chr22_471 ┆ chr22_47 │
│ ---       ┆ 7         ┆ 5         ┆ 5         ┆   ┆ 49267     ┆ 49279     ┆ 49283     ┆ 149298   │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000007028 ┆ 0.13      ┆ 0.13      ┆ 0.31      ┆ … ┆ 0.25      ┆ 0.46      ┆ 0.42      ┆ 0.15     │
│ 770       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000007028 ┆ 0.27      ┆ 0.46      ┆ 0.46      ┆ … ┆ 0.36      ┆ 0.6       ┆ 0.5       ┆ 0.36     │
│ 880       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000007029 ┆ 0.45      ┆ 0.35      ┆ 0.4       ┆ … ┆ 0.63      ┆ 0.72      ┆ 0.68      ┆ 0.71     │
│ 030       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000007029 ┆ 0.47      ┆ 0.44      ┆ 0.55      ┆ … ┆ 0.93      ┆ 0.75      ┆ 0.93      ┆ 0.87     │
│ 040       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000007029 ┆ 0.43      ┆ 0.46      ┆ 0.38      ┆ … ┆ 0.75      ┆ 0.88      ┆ 0.89      ┆ 0.7      │
│ 220       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 000027007 ┆ 0.26      ┆ 0.24      ┆ 0.37      ┆ … ┆ 0.6       ┆ 0.53      ┆ 0.4       ┆ 0.6      │
│ 830       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000027007 ┆ 0.35      ┆ 0.42      ┆ 0.24      ┆ … ┆ 0.0       ┆ 0.12      ┆ 0.33      ┆ 0.1      │
│ 840       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000027007 ┆ 0.73      ┆ 0.85      ┆ 0.85      ┆ … ┆ 0.57      ┆ 0.5       ┆ 0.4       ┆ 0.0      │
│ 900       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000027007 ┆ 0.5       ┆ 0.5       ┆ 0.58      ┆ … ┆ 0.46      ┆ 0.36      ┆ 0.41      ┆ 0.38     │
│ 990       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000027008 ┆ 0.28      ┆ 0.47      ┆ 0.35      ┆ … ┆ 0.2       ┆ 0.12      ┆ 0.22      ┆ 0.06     │
│ 020       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
data_train_full = data_train_raw.select([col for col in data_train_raw.columns if data_train_raw[col].null_count() == 0])
data_train_full.write_csv(step_folder / "data_train_raw.csv")
data_train_full

shape: (76, 191_919)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ btk_id    ┆ chr1_2160 ┆ chr1_2161 ┆ chr1_2168 ┆ … ┆ chr22_471 ┆ chr22_471 ┆ chr22_471 ┆ chr22_47 │
│ ---       ┆ 7         ┆ 5         ┆ 5         ┆   ┆ 49267     ┆ 49279     ┆ 49283     ┆ 149298   │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000007028 ┆ 0.13      ┆ 0.13      ┆ 0.31      ┆ … ┆ 0.25      ┆ 0.46      ┆ 0.42      ┆ 0.15     │
│ 770       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000007028 ┆ 0.27      ┆ 0.46      ┆ 0.46      ┆ … ┆ 0.36      ┆ 0.6       ┆ 0.5       ┆ 0.36     │
│ 880       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000007029 ┆ 0.45      ┆ 0.35      ┆ 0.4       ┆ … ┆ 0.63      ┆ 0.72      ┆ 0.68      ┆ 0.71     │
│ 030       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000007029 ┆ 0.47      ┆ 0.44      ┆ 0.55      ┆ … ┆ 0.93      ┆ 0.75      ┆ 0.93      ┆ 0.87     │
│ 040       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000007029 ┆ 0.43      ┆ 0.46      ┆ 0.38      ┆ … ┆ 0.75      ┆ 0.88      ┆ 0.89      ┆ 0.7      │
│ 220       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 000027007 ┆ 0.26      ┆ 0.24      ┆ 0.37      ┆ … ┆ 0.6       ┆ 0.53      ┆ 0.4       ┆ 0.6      │
│ 830       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000027007 ┆ 0.35      ┆ 0.42      ┆ 0.24      ┆ … ┆ 0.0       ┆ 0.12      ┆ 0.33      ┆ 0.1      │
│ 840       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000027007 ┆ 0.73      ┆ 0.85      ┆ 0.85      ┆ … ┆ 0.57      ┆ 0.5       ┆ 0.4       ┆ 0.0      │
│ 900       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000027007 ┆ 0.5       ┆ 0.5       ┆ 0.58      ┆ … ┆ 0.46      ┆ 0.36      ┆ 0.41      ┆ 0.38     │
│ 990       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000027008 ┆ 0.28      ┆ 0.47      ┆ 0.35      ┆ … ┆ 0.2       ┆ 0.12      ┆ 0.22      ┆ 0.06     │
│ 020       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
btk_id = data_train_full["btk_id"].to_list()
locuses = data_train_full.columns[1:]
data_train_full_T = data_train_full.drop("btk_id").transpose()
data_train_full_T.columns = btk_id
data_train_full_T = pl.concat([data_train_full_T, pl.DataFrame(locuses,schema={"locus":pl.String})],how = "horizontal")
normal_id = sample_train.loc[sample_train["group"] == "Normal","btk_id"].to_list()
kabuki_id = sample_train.loc[sample_train["group"] == "Kabuki","btk_id"].to_list()
sotos_id = sample_train.loc[sample_train["group"] == "Sotos","btk_id"].to_list()
rsts_id = sample_train.loc[sample_train["group"] == "RSTS","btk_id"].to_list()
data_train_full_T_RSS = data_train_full_T.with_columns(
    pl.mean_horizontal(pl.all().exclude(["locus"])).alias("mean_total"),
    pl.mean_horizontal(normal_id).alias("mean_normal"),
    pl.mean_horizontal(kabuki_id).alias("mean_kabuki"),
    pl.mean_horizontal(sotos_id).alias("mean_sotos"),
    pl.mean_horizontal(rsts_id).alias("mean_rsts")    
).with_columns(
    SSW = pl.sum_horizontal([(pl.col(c) - pl.col("mean_normal")).pow(2) for c in normal_id]) + pl.sum_horizontal([(pl.col(c) - pl.col("mean_kabuki")).pow(2) for c in kabuki_id]) + pl.sum_horizontal([(pl.col(c) - pl.col("mean_sotos")).pow(2) for c in sotos_id]) + pl.sum_horizontal([(pl.col(c) - pl.col("mean_rsts")).pow(2) for c in rsts_id]),
    SSB = (len(normal_id) * (pl.col("mean_normal") - pl.col("mean_total")).pow(2)) + (len(kabuki_id) * (pl.col("mean_kabuki") - pl.col("mean_total")).pow(2)) + (len(sotos_id) * (pl.col("mean_sotos") - pl.col("mean_total")).pow(2)) + (len(rsts_id) * (pl.col("mean_rsts") - pl.col("mean_total")).pow(2))
)
low_SSW_high_SSB = data_train_full_T_RSS.filter(
    (pl.col("SSW") <= pl.col("SSW").quantile(parameters['SSW_QUANTILE_THRESHOLD'])) & (pl.col("SSB") >= pl.col("SSB").quantile(parameters['SSB_QUANTILE_THRESHOLD']))
)
low_SSW_high_SSB

shape: (4_595, 84)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬──────────┐
│ 0000070287 ┆ 000007028 ┆ 000007029 ┆ 000007029 ┆ … ┆ mean_soto ┆ mean_rsts ┆ SSW      ┆ SSB      │
│ 70         ┆ 880       ┆ 030       ┆ 040       ┆   ┆ s         ┆ ---       ┆ ---      ┆ ---      │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64      ┆ f64      │
│ f64        ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆           ┆          ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪══════════╡
│ 0.9        ┆ 0.93      ┆ 1.0       ┆ 1.0       ┆ … ┆ 0.194     ┆ 0.954615  ┆ 0.506864 ┆ 4.794129 │
│ 0.84       ┆ 0.93      ┆ 0.9       ┆ 1.0       ┆ … ┆ 0.184     ┆ 0.936923  ┆ 0.584636 ┆ 4.546031 │
│ 0.6        ┆ 0.47      ┆ 0.78      ┆ 0.55      ┆ … ┆ 0.113     ┆ 0.891538  ┆ 1.051924 ┆ 3.822712 │
│ 0.82       ┆ 0.75      ┆ 0.89      ┆ 0.73      ┆ … ┆ 0.307     ┆ 0.952308  ┆ 0.700929 ┆ 3.017744 │
│ 0.86       ┆ 0.88      ┆ 0.81      ┆ 0.73      ┆ … ┆ 0.142     ┆ 0.828462  ┆ 0.547143 ┆ 4.254373 │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …        │
│ 0.5        ┆ 0.5       ┆ 0.75      ┆ 0.69      ┆ … ┆ 0.099     ┆ 0.712308  ┆ 1.470564 ┆ 3.067156 │
│ 0.33       ┆ 0.89      ┆ 1.0       ┆ 0.85      ┆ … ┆ 0.25      ┆ 0.907692  ┆ 1.231619 ┆ 3.021997 │
│ 0.94       ┆ 0.94      ┆ 1.0       ┆ 1.0       ┆ … ┆ 0.361     ┆ 0.873846  ┆ 0.717884 ┆ 2.432414 │
│ 1.0        ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 0.991538  ┆ 1.492538 ┆ 5.23835  │
│ 1.0        ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 0.986923  ┆ 1.368292 ┆ 4.996996 │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴──────────┘

In [19]:
X_train = low_SSW_high_SSB.select(cs.starts_with("0000")).transpose(column_names = low_SSW_high_SSB["locus"])
y_train = sample_train["group"].to_numpy()
y_label = sample_train["id"].to_numpy()
y_btk = sample_train["btk_id"].to_numpy()
X_train.write_csv(step_folder / "X_train.csv")
np.save(step_folder / "y_train.npy", y_train)
np.save(step_folder / "y_label.npy", y_label)
np.save(step_folder / "y_btk.npy", y_btk)